Twitter:
  access_token: '4704095618-TFFO6NutEYXQKQVhyZ4n1KWQ5bzzV6WmStIKVkm'
  access_token_secret: 'Ojuvnd03S90q18iiBQsy2x48Ybh2UtmyHIcw0LMqN0tmp'
  consumer_key: 'hDb0prUCcJivdIOPvRx8Q0MFa'
  consumer_secret: 'OiqhU0gDoz53NOn3eFnxLC6OBtTEEDwdtPBkOZrj0bKBH4CbWD'

Discord:
  - track:
     - 'python'
    webhook_urls:
     - 'https://discord.com/api/webhooks/919239791718060083/EhGawowLTPG6KF7KA5rQC0y6ovlXNplZCJmCwmVhyCuIyWmECVhCL_7ZuAr9dP7tBMf5'
