Twitter:
  access_token: '4704095618-JyTEGioCqBICxFNoW4CGDkC9pxIEXE9pUr7k4tB'
  access_token_secret: '0xgBW37YqihydKt1f5TP7VsTL3zMMvyZQXvaTsWv1AB89'
  consumer_key: 'llr2tLZyXgBcrUm0pIhKNKpca'
  consumer_secret: 'm2TB4CdqH7jO2bRkidtAlHqNvOqbmrRThCG4HRcAp9ILJouYLY'

Discord:
  - track:
     - 'python'
    webhook_urls:
     - 'https://discord.com/api/webhooks/919239791718060083/EhGawowLTPG6KF7KA5rQC0y6ovlXNplZCJmCwmVhyCuIyWmECVhCL_7ZuAr9dP7tBMf5'
